# Generated by Django 4.2.3 on 2023-09-26 12:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('pass_token', models.CharField(max_length=32)),
                ('text', models.TextField()),
                ('stamp', models.IntegerField()),
            ],
        ),
    ]
